In [2]:
import sys
import re
import numpy as np
import pandas as pd
import pysam
import matplotlib.pyplot as plt
import seaborn as sns

In [68]:
fpath = "/scratch/indikar_root/indikar1/cstansbu/scpc_test/vcf/f1219.snps.tsv"
df = pd.read_csv(fpath, sep="\t", low_memory=False)
df.columns = ['chrom', 'pos', 'ref', 'alt', '129S1_SvImJ', 'CAST_EiJ']

df['129S1_SvImJ'] = df['129S1_SvImJ'].str.replace('129S1_SvImJ=', '')
df['CAST_EiJ'] = df['CAST_EiJ'].str.replace('CAST_EiJ=', '')

print(f"{df.shape=}")
print(df.columns)
df.head()

df.shape=(80557382, 6)
Index(['chrom', 'pos', 'ref', 'alt', '129S1_SvImJ', 'CAST_EiJ'], dtype='object')

  chrom      pos ref alt 129S1_SvImJ CAST_EiJ
0     1  3050050   C   G         0/0      0/0
1     1  3050069   C   T         1/1      0/1
2     1  3050076   C   T         0/0      0/0
3     1  3050115   G   A         0/0      0/0
4     1  3050118   G   A         0/0      0/0

In [69]:
haplo_map = {
    '0/0' : 'homozygous reference',
    '0/1' : 'heterozygous',
    '1/1' : 'homozygous alternate',
}

df['129S1_SvImJ_type'] = df['129S1_SvImJ'].map(haplo_map)
df['CAST_EiJ_type'] = df['CAST_EiJ'].map(haplo_map)
df.head()

,chrom,pos,ref,alt,129S1_SvImJ,CAST_EiJ,129S1_SvImJ_type,CAST_EiJ_type
0,1,3050050,C,G,0/0,0/0,homozygous reference,homozygous reference
1,1,3050069,C,T,1/1,0/1,homozygous alternate,heterozygous
2,1,3050076,C,T,0/0,0/0,homozygous reference,homozygous reference
3,1,3050115,G,A,0/0,0/0,homozygous reference,homozygous reference
4,1,3050118,G,A,0/0,0/0,homozygous reference,homozygous reference

In [71]:
df['129S1_SvImJ_type'].value_counts(normalize=True, dropna=False)

129S1_SvImJ_type
homozygous reference    0.924582
homozygous alternate    0.066347
heterozygous            0.009071
Name: proportion, dtype: float64

In [72]:
df['CAST_EiJ_type'].value_counts(normalize=True, dropna=False)

CAST_EiJ_type
homozygous reference    0.716855
homozygous alternate    0.258103
heterozygous            0.025042
Name: proportion, dtype: float64

In [ ]:
break

In [62]:
vcf_path = "/nfs/turbo/umms-indikar/shared/projects/poreC/data/VCFs/f1219.vcf.gz"
outpath = "/nfs/turbo/umms-indikar/shared/projects/poreC/data/VCFs/test.vcf.gz"

vcf_file = pysam.VariantFile(vcf_path) 
vcf_file_out = pysam.VariantFile(outpath, 'w', header=vcf_file.header)

recs = 1000000
counter = -1

for rec in vcf_file:
    counter += 1
    if counter == recs:
        break
        
    lookup = dict(rec.samples)

    for sample_name, sample_record in lookup.items():
        alleles = sample_record.alleles

        if alleles is None:
            continue
    
        if len(alleles) != 2:
            continue

        # print(sample_name, "".join(alleles))

        if "." in "".join([str(x) for x in alleles]):
            print(alleles)
    
    # print(f"{rec.chrom=}")
    # print(f"{rec.pos=}")
    # print(f"{rec.ref=}")
    # print(f"{rec.alts=}")
    # print(f"{rec.id=}")
    # print(f"{rec.samples['CAST_EiJ'].alleles=}")
    # print(f"{rec.samples['129S1_SvImJ'].alleles=}")

    
    
    
    # print(dict(rec.samples))

    # print(rec['CAST_EiJ'])
    # break

In [29]:
dir(rec.samples['CAST_EiJ'])

['__bool__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'allele_indices',
 'alleles',
 'clear',
 'get',
 'index',
 'items',
 'iteritems',
 'iterkeys',
 'itervalues',
 'keys',
 'name',
 'phased',
 'pop',
 'update',
 'values']

In [21]:
dir(rec)

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'alleles',
 'alleles_variant_types',
 'alts',
 'chrom',
 'contig',
 'copy',
 'filter',
 'format',
 'header',
 'id',
 'info',
 'pos',
 'qual',
 'ref',
 'rid',
 'rlen',
 'samples',
 'start',
 'stop',
 'translate']

In [13]:
fpath = "/scratch/indikar_root/indikar1/cstansbu/scpc_test/vcf/f1219.snps.tsv"
df = pd.read_csv(fpath, sep="\t")
print(f"{df.shape=}")
df.head()

/tmp/ipykernel_2138899/1651383413.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(fpath, sep="\t")

df.shape=(82096058, 6)

,# [1]CHROM,[2]POS,[3]REF,[4]ALT,[5]SAMPLE=[6]129S1_SvImJ:GT,[7]SAMPLE=[8]CAST_EiJ:GT
0,1,3050050,C,G,129S1_SvImJ=0/0,CAST_EiJ=0/0
1,1,3050069,C,T,129S1_SvImJ=1/1,CAST_EiJ=0/1
2,1,3050076,C,T,129S1_SvImJ=0/0,CAST_EiJ=0/0
3,1,3050115,G,A,129S1_SvImJ=0/0,CAST_EiJ=0/0
4,1,3050118,G,A,129S1_SvImJ=0/0,CAST_EiJ=0/0

In [12]:
for chrom, group in df.groupby('CHROM'):

    group['next_pos'] = group['POS'].shift(1)
    group['pos_diff'] = group['POS'] - group['next_pos']
    print(f"===== {chrom} ({group['pos_diff'].mean():.3f}) =====")
    # break

===== 1 (29.772) =====
===== 2 (32.719) =====
===== 3 (29.302) =====
===== 4 (30.356) =====
===== 5 (30.528) =====
===== 6 (28.721) =====
===== 7 (29.985) =====
===== 8 (30.333) =====
===== 9 (31.120) =====
===== 10 (29.928) =====
===== 11 (31.452) =====
===== 12 (29.162) =====
===== 13 (30.281) =====
===== 14 (31.259) =====
===== 15 (29.655) =====
===== 16 (30.069) =====
===== 17 (28.699) =====
===== 18 (30.401) =====
===== 19 (30.088) =====
===== 19 (43.447) =====
===== X (45.173) =====